import type { Translations } from './types';

export const translations: { en: Translations; ar: Translations } = {
  en: {
    title: "Tailors Payroll System",
    addEntry: "Add New Entry",
    workerName: "Worker's Name",
    date: "Date",
    itemsDelivered: "Items Delivered",
    pricePerItem: "Price per Item",
    dailyTotal: "Daily Total",
    currency: "AED",
    submit: "Add Entry",
    dailyLog: "Daily Entries Log",
    delete: "Delete",
    monthlySummary: "Monthly Summary",
    totalItems: "Total Items",
    totalSalary: "Total Salary (AED)",
    exportToCSV: "Export to CSV",
    noEntries: "No daily entries have been added for this month.",
    noSummary: "No summary to display for this month.",
    confirmClear: "Are you sure you want to delete all entries? This action cannot be undone.",
    clearData: "Clear All Data",
    formValidation: {
      workerName: "Worker's name is required.",
      date: "Date is required.",
      items: "Number of items must be a positive number.",
      price: "Price must be a positive number."
    },
    configTitle: "Setup Google Sheets Connection",
    configInstructions: "To get started, deploy the Google Apps Script and paste your Web App URL below.",
    appsScriptUrl: "Google Apps Script URL",
    saveUrl: "Save and Connect",
    urlRequired: "A valid Google Apps Script URL is required.",
    month: "Month",
    loading: "Loading data...",
    apiError: "Failed to communicate with Google Sheets. Please check the URL and script permissions.",
    changeConfig: "Change Google Sheets URL",
    confirmClearConfig: "Are you sure you want to disconnect from Google Sheets? You will need to re-enter the URL.",
    entryAddedSuccess: "Entry added successfully!",
    entryAddedError: "Failed to add entry. Please try again.",
    baseSalary: "Base Salary",
    finalSalary: "Final Salary",
    manageSalaries: "Manage Base Salaries",
    saveSalaries: "Save Changes",
    pieceworkSalary: "Piecework Salary",
    advance: "Advance / Deduction",
    manageAdvances: "Manage Advances",
    saveAdvances: "Save Advances",
    aiAssistant: "AI Payroll Assistant",
    askAnything: "Ask anything about this month's data...",
    analyzing: "Analyzing...",
    aiError: "Sorry, I couldn't process that. Please try again.",
    openChat: "Open AI Assistant",
    closeChat: "Close AI Assistant",
    manageWorkers: "Manage Workers",
    changePhoto: "Change Photo",
    deleteWorker: "Delete",
    confirmDeleteWorker: "Are you sure you want to delete this worker's profile? This cannot be undone.",
    workerProfileUpdated: "Worker profile updated.",
    workerProfileDeleted: "Worker profile deleted.",
    quickSelect: "Quick Select",
    noWorkersYet: "No workers saved yet. Add an entry to save a worker.",
    photo: "Photo",
    actions: "Actions",
    markAsPaid: "Mark as Paid",
    unmarkAsPaid: "Unmark",
    paidOn: "Paid on",
    editNotes: "Edit Notes",
    confirmPaymentTitle: "Confirm Payment",
    paymentNotes: "Payment Notes (optional)",
    paymentNotesPlaceholder: "e.g., Paid via bank transfer",
    confirmAndSave: "Confirm & Save",
    confirmUnmarkPayment: "Are you sure you want to unmark this payment?",
    paymentMarkedSuccess: "Payment marked as complete.",
    paymentUnmarkedSuccess: "Payment status reset.",
    notesSavedSuccess: "Payment notes updated.",
    noNotes: "No notes.",
    paymentStatus: "Payment Status",
    paymentDate: "Payment Date",
    paymentNotesCSV: "Payment Notes",
    paid: "Paid",
    unpaid: "Unpaid",
  },
  ar: {
    title: "نظام حساب رواتب الخياطين",
    addEntry: "إضافة إدخال جديد",
    workerName: "اسم العامل",
    date: "التاريخ",
    itemsDelivered: "عدد القطع المسلمة",
    pricePerItem: "سعر القطعة",
    dailyTotal: "المجموع اليومي",
    currency: "درهم",
    submit: "إضافة إدخال",
    dailyLog: "سجل الإدخالات اليومية",
    delete: "حذف",
    monthlySummary: "الملخص الشهري",
    totalItems: "إجمالي القطع",
    totalSalary: "إجمالي الراتب (درهم)",
    exportToCSV: "تصدير إلى CSV",
    noEntries: "لم يتم إضافة أي إدخالات يومية لهذا الشهر.",
    noSummary: "لا يوجد ملخص لعرضه لهذا الشهر.",
    confirmClear: "هل أنت متأكد من رغبتك في حذف جميع الإدخالات؟ لا يمكن التراجع عن هذا الإجراء.",
    clearData: "مسح كل البيانات",
    formValidation: {
      workerName: "اسم العامل مطلوب.",
      date: "التاريخ مطلوب.",
      items: "يجب أن يكون عدد العناصر رقمًا موجبًا.",
      price: "يجب أن يكون السعر رقمًا موجبًا."
    },
    configTitle: "إعداد الاتصال بجداول جوجل",
    configInstructions: "للبدء، قم بنشر Google Apps Script والصق عنوان URL لتطبيق الويب أدناه.",
    appsScriptUrl: "عنوان URL لـ Google Apps Script",
    saveUrl: "حفظ والاتصال",
    urlRequired: "مطلوب عنوان URL صالح لـ Google Apps Script.",
    month: "الشهر",
    loading: "جاري تحميل البيانات...",
    apiError: "فشل الاتصال بجداول جوجل. يرجى التحقق من عنوان URL وأذونات السكريبت.",
    changeConfig: "تغيير عنوان URL لجداول جوجل",
    confirmClearConfig: "هل أنت متأكد من رغبتك في قطع الاتصال بجداول جوجل؟ ستحتاج إلى إعادة إدخال عنوان URL.",
    entryAddedSuccess: "تمت إضافة الإدخال بنجاح!",
    entryAddedError: "فشل في إضافة الإدخال. يرجى المحاولة مرة أخرى.",
    baseSalary: "الراتب الأساسي",
    finalSalary: "الراتب النهائي",
    manageSalaries: "إدارة الرواتب الأساسية",
    saveSalaries: "حفظ التغييرات",
    pieceworkSalary: "راتب القطعة",
    advance: "السلفة / الخصم",
    manageAdvances: "إدارة السلف",
    saveAdvances: "حفظ السلف",
    aiAssistant: "مساعد الرواتب الذكي",
    askAnything: "اسأل أي شيء عن بيانات هذا الشهر...",
    analyzing: "جاري التحليل...",
    aiError: "عذراً، لم أتمكن من معالجة ذلك. يرجى المحاولة مرة أخرى.",
    openChat: "فتح مساعد الذكاء الاصطناعي",
    closeChat: "إغلاق مساعد الذكاء الاصطناعي",
    manageWorkers: "إدارة العمال",
    changePhoto: "تغيير الصورة",
    deleteWorker: "حذف",
    confirmDeleteWorker: "هل أنت متأكد من حذف ملف هذا العامل؟ لا يمكن التراجع عن هذا الإجراء.",
    workerProfileUpdated: "تم تحديث ملف العامل.",
    workerProfileDeleted: "تم حذف ملف العامل.",
    quickSelect: "اختيار سريع",
    noWorkersYet: "لم يتم حفظ أي عمال بعد. أضف إدخالاً لحفظ عامل.",
    photo: "الصورة",
    actions: "الإجراءات",
    markAsPaid: "تحديد كمدفوع",
    unmarkAsPaid: "إلغاء الدفع",
    paidOn: "مدفوع بتاريخ",
    editNotes: "تعديل الملاحظات",
    confirmPaymentTitle: "تأكيد الدفع",
    paymentNotes: "ملاحظات الدفع (اختياري)",
    paymentNotesPlaceholder: "مثال: تم الدفع عبر تحويل بنكي",
    confirmAndSave: "تأكيد وحفظ",
    confirmUnmarkPayment: "هل أنت متأكد من رغبتك في إلغاء تحديد هذا الدفع؟",
    paymentMarkedSuccess: "تم تحديد الدفعة كمكتملة.",
    paymentUnmarkedSuccess: "تمت إعادة تعيين حالة الدفع.",
    notesSavedSuccess: "تم تحديث ملاحظات الدفع.",
    noNotes: "لا توجد ملاحظات.",
    paymentStatus: "حالة الدفع",
    paymentDate: "تاريخ الدفع",
    paymentNotesCSV: "ملاحظات الدفع",
    paid: "مدفوع",
    unpaid: "غير مدفوع",
  },
};
